### ISSUE TITLE
Remove Langtrace

### ISSUE THREAD

**Issue by whoabuddy** [aibtcdev/aibtcdev-backend#61]
We've blown through the 10k per month trace limit by 2x already and things are just getting started! We can do our own logging with the callbacks instead, which gives us more options on what we can display in the front-end too.

**Comment by whoabuddy** [comment]
Removed in 0fbb321

**Comment by karthikscale3** [comment]
Found this randomly. Langtrace core maintainer here. Just ping us on our chat and we are happy to bump your free tier limits.
