### ISSUE TITLE
Incorrect asset identifier for sBTC in Hiro API

### ISSUE THREAD

**Issue by whoabuddy** [aibtcdev/aibtcdev-backend#85]
Following the quick fix in #84 we need to investigate why the asset identifier for sBTC wasn't correctly resolved from the Hiro token metadata API. Maybe a bug?

**Comment by human058382928** [comment]
It was a bug on hiro api. Created ticket in the tools repo to revert hotfix.

https://github.com/aibtcdev/agent-tools-ts/issues/72
